// The weapon registry: every gun the class screen can offer, the knife, and
// the two grenades, in one table. index.html builds its weapon slots, the
// class-screen cards, the HUD names and the bots' loadouts from here, so
// adding a weapon is one entry (generated by
// `python .tools/generate_weapon_definitions.py <id>`) plus its assets
// (`python .tools/import_weapon_assets.py`).
//
// Stats are the T6 weapon files' own: magazine, cadence, fire type, damage
// and the authored clip names. Range falloff, spread and kick live in
// weapon-ballistics.js, generated from the same files. No DOM or Three.js
// here so the table loads in node tests.

const degToRad = (degrees) => degrees * (Math.PI / 180);

// Create-a-class tabs, in the game's order. Each holds one equipped weapon.
export const WEAPON_CLASSES = Object.freeze({
  primary: Object.freeze({ id: 'primary', label: 'Primary', hint: 'Assault and sniper rifles', key: 'Digit1' }),
  secondary: Object.freeze({ id: 'secondary', label: 'Secondary', hint: 'Pistols', key: 'Digit2' }),
  lethal: Object.freeze({ id: 'lethal', label: 'Lethal', hint: 'Thrown with G', key: 'KeyG' }),
  tactical: Object.freeze({ id: 'tactical', label: 'Tactical', hint: 'Thrown with Q', key: 'KeyQ' }),
});
export const WEAPON_CLASS_IDS = Object.freeze(Object.keys(WEAPON_CLASSES));

export const WEAPONS = Object.freeze({
  m27: Object.freeze({
    id: 'm27',
    name: 'M27',
    class: 'primary',
    role: 'Assault rifle',
    slot: 1,
    // The weapon files and soundbanks name the M27 by its source id.
    sourceId: 'hk416',
    magazineSize: 30,
    reserveAmmo: 240,
    roundsPerMinute: 750,
    fireMode: 'auto',
    damage: 33,
    fireTypeIcon: 'hud_mp_firerate_auto',
    cardArt: 'ui/menu_mp_weapons_hk416_big.png',
    viewmodelUrl: 'viewmodel/t6_wpn_ar_hk416_view_lod0.glb',
    worldModelUrl: 'enemies/t6_wpn_ar_hk416_world_lod1.glb',
    magazineUrl: 'viewmodel/t6_attach_mag_hk416_view_lod0.glb',
    // Authored attachment offset from the shipped hk416_mp weapon file.
    magazineOffset: Object.freeze([3.389, 0, -0.383]),
    clips: Object.freeze({
      idle: 'viewmodel/anims/viewmodel_hk416_idle.json',
      fire: 'viewmodel/anims/viewmodel_hk416_fire.json',
      adsFire: 'viewmodel/anims/viewmodel_hk416_ads_fire.json',
      reload: 'viewmodel/anims/viewmodel_hk416_reload.json',
      reloadEmpty: 'viewmodel/anims/viewmodel_hk416_reload_empty.json',
    }),
  }),
  an94: Object.freeze({
    id: 'an94',
    name: 'AN-94',
    class: 'primary',
    role: 'Assault rifle',
    slot: 2,
    sourceId: 'an94',
    magazineSize: 30,
    reserveAmmo: 240,
    roundsPerMinute: 625,
    fireMode: 'auto',
    initialRoundsPerMinute: 937.5,
    initialShotCount: 2,
    damage: 40,
    fireTypeIcon: 'hud_mp_firerate_auto',
    cardArt: 'ui/menu_mp_weapons_an94_big.png',
    adsFov: 50,
    viewmodelUrl: 'viewmodel/t6_wpn_ar_an94_view_lod0.glb',
    worldModelUrl: 'enemies/t6_wpn_ar_an94_world_lod1.glb',
    magazineUrl: 'viewmodel/t6_attach_mag_an94_view_lod0.glb',
    // Authored attachment offsets from the shipped an94_mp weapon file.
    magazineOffset: Object.freeze([4.473, -1.085, -1.5]),
    // T6's roll is around the weapon's forward X axis. The GLB weld applies
    // the engine-to-view transform after this attachment transform.
    magazineRotation: Object.freeze([degToRad(-15), 0, 0]),
    clips: Object.freeze({
      idle: 'viewmodel/anims/viewmodel_an94_idle.json',
      introFire: 'viewmodel/anims/viewmodel_an94_intro_fire.json',
      fire: 'viewmodel/anims/viewmodel_an94_fire.json',
      introAdsFire: 'viewmodel/anims/viewmodel_an94_intro_ads_fire.json',
      adsFire: 'viewmodel/anims/viewmodel_an94_ads_fire.json',
      reload: 'viewmodel/anims/viewmodel_an94_reload.json',
      reloadEmpty: 'viewmodel/anims/viewmodel_an94_reload_empty.json',
    }),
  }),
  sa58: Object.freeze({
    id: 'sa58',
    name: 'FAL OSW',
    class: 'primary',
    role: 'Assault rifle',
    slot: 3,
    sourceId: 'sa58',
    magazineSize: 25,
    reserveAmmo: 240,
    roundsPerMinute: 625,
    fireMode: 'single',
    damage: 55,
    fireTypeIcon: 'hud_mp_firerate_single',
    cardArt: 'ui/menu_mp_weapons_sa58_big.png',
    viewmodelUrl: 'viewmodel/t6_wpn_ar_sa58_view_lod0.glb',
    worldModelUrl: 'enemies/t6_wpn_ar_sa58_world_lod1.glb',
    magazineUrl: 'viewmodel/t6_attach_mag_sa58_view_lod0.glb',
    // Authored attachment offset from the shipped sa58_mp weapon file.
    magazineOffset: Object.freeze([4.006, 0.015, 1.821]),
    magazineRotation: Object.freeze([0, 0, 0]),
    // Measured sight opening/post in j_gun coordinates (inches).
    adsSightAnchors: Object.freeze({
      rear: Object.freeze([-3.62, 0, 4.465]),
    }),
    clips: Object.freeze({
      idle: 'viewmodel/anims/viewmodel_sa58_idle.json',
      fire: 'viewmodel/anims/viewmodel_sa58_fire.json',
      adsFire: 'viewmodel/anims/viewmodel_sa58_ads_fire.json',
      reload: 'viewmodel/anims/viewmodel_sa58_reload.json',
      reloadEmpty: 'viewmodel/anims/viewmodel_sa58_reload_empty.json',
    }),
  }),
  saritch: Object.freeze({
    id: 'saritch',
    name: 'SMR',
    class: 'primary',
    role: 'Assault rifle',
    slot: 4,
    sourceId: 'saritch',
    magazineSize: 20,
    reserveAmmo: 240,
    roundsPerMinute: 536,
    fireMode: 'single',
    damage: 50,
    fireTypeIcon: 'hud_mp_firerate_single',
    cardArt: 'ui/menu_mp_weapons_saritch_big.png',
    hiddenTags: Object.freeze(["tag_sights_off"]),
    viewmodelUrl: 'viewmodel/t6_wpn_ar_saritch_view_lod0.glb',
    worldModelUrl: 'enemies/t6_wpn_ar_saritch_world_lod1.glb',
    magazineUrl: 'viewmodel/t6_attach_mag_saritch_view_lod0.glb',
    // Authored attachment offset from the shipped saritch_mp weapon file.
    magazineOffset: Object.freeze([-8.907, 0, -2.646]),
    magazineRotation: Object.freeze([0, 0, 0]),
    // Actual front post tip and centre of the rear aperture, in j_gun space.
    adsSightAnchors: Object.freeze({
      front: Object.freeze([12.672, 0, 3.924]),
      rear: Object.freeze([-2.547, 0, 3.958]),
    }),
    clips: Object.freeze({
      idle: 'viewmodel/anims/viewmodel_saritch_idle.json',
      fire: 'viewmodel/anims/viewmodel_saritch_fire.json',
      adsFire: 'viewmodel/anims/viewmodel_saritch_ads_fire.json',
      reload: 'viewmodel/anims/viewmodel_saritch_reload.json',
      reloadEmpty: 'viewmodel/anims/viewmodel_saritch_reload_empty.json',
    }),
  }),
  scar: Object.freeze({
    id: 'scar',
    name: 'SCAR-H',
    class: 'primary',
    role: 'Assault rifle',
    slot: 5,
    sourceId: 'scar',
    magazineSize: 30,
    reserveAmmo: 240,
    roundsPerMinute: 625,
    fireMode: 'auto',
    damage: 40,
    fireTypeIcon: 'hud_mp_firerate_auto',
    cardArt: 'ui/menu_mp_weapons_scar_big.png',
    hiddenTags: Object.freeze(["tag_sights_off"]),
    viewmodelUrl: 'viewmodel/t6_wpn_ar_scarh_view_lod0.glb',
    worldModelUrl: 'enemies/t6_wpn_ar_scarh_world_lod1.glb',
    magazineUrl: 'viewmodel/t6_attach_mag_scar_view_lod0.glb',
    // Authored attachment offset from the shipped scar_mp weapon file.
    magazineOffset: Object.freeze([3.716, 0, -0.345]),
    magazineRotation: Object.freeze([0, 0, 0]),
    // No tritium insert, and this rig is the awkward one: its sight hood reaches
    // the centreline and stands 0.54 above the post, so the obvious reading of
    // the geometry measures the hood and tilts the sight line up toward the
    // muzzle. measure_sights.mjs falls back to a narrow-blade search here.
    adsSightAnchors: Object.freeze({
      front: Object.freeze([13.515, 0, 4.846]),
      rear: Object.freeze([-2.237, 0, 4.894]),
    }),
    clips: Object.freeze({
      idle: 'viewmodel/anims/viewmodel_scar_h_idle.json',
      fire: 'viewmodel/anims/viewmodel_scar_h_fire.json',
      adsFire: 'viewmodel/anims/viewmodel_scar_h_ads_fire.json',
      reload: 'viewmodel/anims/viewmodel_scar_h_reload.json',
      reloadEmpty: 'viewmodel/anims/viewmodel_scar_h_reload_empty.json',
    }),
  }),
  sig556: Object.freeze({
    id: 'sig556',
    name: 'SWAT-556',
    class: 'primary',
    role: 'Assault rifle',
    slot: 6,
    sourceId: 'sig556',
    magazineSize: 30,
    reserveAmmo: 240,
    roundsPerMinute: 938,
    fireMode: 'burst',
    burstCount: 3,
    damage: 40,
    fireTypeIcon: 'hud_mp_firerate_burst',
    cardArt: 'ui/menu_mp_weapons_sig556_big.png',
    hiddenTags: Object.freeze(["tag_sights_off"]),
    viewmodelUrl: 'viewmodel/t6_wpn_ar_sig556_view_lod0.glb',
    worldModelUrl: 'enemies/t6_wpn_ar_sig556_world_lod1.glb',
    magazineUrl: 'viewmodel/t6_attach_mag_sig556_view_lod0.glb',
    // Authored attachment offset from the shipped sig556_mp weapon file.
    magazineOffset: Object.freeze([5.663, -0.008, -0.815]),
    magazineRotation: Object.freeze([0, 0, 0]),
    // Actual front post tip and centre of the rear aperture, in j_gun space.
    adsSightAnchors: Object.freeze({
      front: Object.freeze([19.739, 0, 5.155]),
      rear: Object.freeze([1.044, 0, 5.177]),
    }),
    clips: Object.freeze({
      idle: 'viewmodel/anims/viewmodel_sig556_idle.json',
      fire: 'viewmodel/anims/viewmodel_sig556_fire.json',
      adsFire: 'viewmodel/anims/viewmodel_sig556_ads_fire.json',
      introFire: 'viewmodel/anims/viewmodel_sig556_fire.json',
      reload: 'viewmodel/anims/viewmodel_sig556_reload.json',
      reloadEmpty: 'viewmodel/anims/viewmodel_sig556_reload_empty.json',
    }),
  }),
  tar21: Object.freeze({
    id: 'tar21',
    name: 'MTAR',
    class: 'primary',
    role: 'Assault rifle',
    slot: 7,
    sourceId: 'tar21',
    magazineSize: 30,
    reserveAmmo: 240,
    roundsPerMinute: 750,
    fireMode: 'auto',
    damage: 40,
    fireTypeIcon: 'hud_mp_firerate_auto',
    cardArt: 'ui/menu_mp_weapons_tar21_big.png',
    hiddenTags: Object.freeze(["tag_sights_off", "tag_gl_on"]),
    viewmodelUrl: 'viewmodel/t6_wpn_ar_x95l_view_lod0.glb',
    worldModelUrl: 'enemies/t6_wpn_ar_x95l_world_lod1.glb',
    magazineUrl: 'viewmodel/t6_attach_mag_x95l_view_lod0.glb',
    // Authored attachment offset from the shipped tar21_mp weapon file.
    magazineOffset: Object.freeze([-9.754, 0, -0.04]),
    magazineRotation: Object.freeze([0, 0, 0]),
    // Measured sight opening/post in j_gun coordinates (inches).
    adsSightAnchors: Object.freeze({
      rear: Object.freeze([-4.6, 0, 3.89]),
    }),
    clips: Object.freeze({
      idle: 'viewmodel/anims/viewmodel_tavor_idle.json',
      fire: 'viewmodel/anims/viewmodel_tavor_fire.json',
      adsFire: 'viewmodel/anims/viewmodel_tavor_ads_fire.json',
      reload: 'viewmodel/anims/viewmodel_tavor_reload.json',
      reloadEmpty: 'viewmodel/anims/viewmodel_tavor_reload_empty.json',
    }),
  }),
  type95: Object.freeze({
    id: 'type95',
    name: 'Type 25',
    class: 'primary',
    role: 'Assault rifle',
    slot: 8,
    sourceId: 'type95',
    magazineSize: 30,
    reserveAmmo: 240,
    roundsPerMinute: 938,
    fireMode: 'auto',
    damage: 33,
    fireTypeIcon: 'hud_mp_firerate_auto',
    cardArt: 'ui/menu_mp_weapons_type95_big.png',
    hiddenTags: Object.freeze(["tag_sights_off", "tag_rails"]),
    viewmodelUrl: 'viewmodel/t6_wpn_ar_type95_view_lod0.glb',
    worldModelUrl: 'enemies/t6_wpn_ar_type95_world_lod1.glb',
    magazineUrl: 'viewmodel/t6_attach_mag_type95_view_lod0.glb',
    // Authored attachment offset from the shipped type95_mp weapon file.
    magazineOffset: Object.freeze([-8.38, 0, -0.678]),
    magazineRotation: Object.freeze([0, 0, 0]),
    // Measured sight opening/post in j_gun coordinates (inches).
    adsSightAnchors: Object.freeze({
      rear: Object.freeze([-5.6, 0, 4.46]),
    }),
    clips: Object.freeze({
      idle: 'viewmodel/anims/viewmodel_type95_ar_idle.json',
      fire: 'viewmodel/anims/viewmodel_type95_ar_fire.json',
      adsFire: 'viewmodel/anims/viewmodel_type95_ar_ads_fire.json',
      introFire: 'viewmodel/anims/viewmodel_type95_ar_fire.json',
      reload: 'viewmodel/anims/viewmodel_type95_ar_reload.json',
      reloadEmpty: 'viewmodel/anims/viewmodel_type95_ar_reload_empty.json',
    }),
  }),
  xm8: Object.freeze({
    id: 'xm8',
    name: 'M8A1',
    class: 'primary',
    role: 'Assault rifle',
    slot: 9,
    sourceId: 'xm8',
    magazineSize: 36,
    reserveAmmo: 240,
    roundsPerMinute: 1250,
    fireMode: 'burst',
    burstCount: 4,
    damage: 35,
    fireTypeIcon: 'hud_mp_firerate_burst',
    cardArt: 'ui/menu_mp_weapons_xm8_big.png',
    hiddenTags: Object.freeze(["tag_sights_off"]),
    viewmodelUrl: 'viewmodel/t6_wpn_ar_xm8_view_lod0.glb',
    worldModelUrl: 'enemies/t6_wpn_ar_xm8_world_lod1.glb',
    magazineUrl: 'viewmodel/t6_attach_mag_xm8_view_lod0.glb',
    // Authored attachment offset from the shipped xm8_mp weapon file.
    magazineOffset: Object.freeze([4.212, 0, 0.279]),
    magazineRotation: Object.freeze([0, 0, 0]),
    // Measured sight opening/post in j_gun coordinates (inches).
    adsSightAnchors: Object.freeze({
      rear: Object.freeze([-1.6, 0, 3.789]),
    }),
    clips: Object.freeze({
      idle: 'viewmodel/anims/viewmodel_xm8_idle.json',
      fire: 'viewmodel/anims/viewmodel_xm8_fire.json',
      adsFire: 'viewmodel/anims/viewmodel_xm8_ads_fire.json',
      introFire: 'viewmodel/anims/viewmodel_xm8_fire.json',
      reload: 'viewmodel/anims/viewmodel_xm8_reload.json',
      reloadEmpty: 'viewmodel/anims/viewmodel_xm8_reload_empty.json',
    }),
  }),

  // Sniper rifles share the primary slot. `scope` is the weapon file's ADS:
  // the world zooms to zoomFov (three slots, all equal without the Variable
  // Zoom attachment), the gun leaves the view and the overlay image stands in
  // for the glass, with idleAmount worth of sway that a held breath steadies.
  // The bolt-actions work the bolt after every shot. The game deals two spare
  // magazines of sniper ammunition.
  dsr50: Object.freeze({
    id: 'dsr50',
    name: 'DSR 50',
    class: 'primary',
    role: 'Sniper rifle',
    slot: 10,
    sourceId: 'dsr50',
    magazineSize: 5,
    reserveAmmo: 10,
    roundsPerMinute: 300,
    fireMode: 'single',
    damage: 98,
    fireTypeIcon: 'hud_mp_firerate_bolt',
    cardArt: 'ui/menu_mp_weapons_dsr50_big.png',
    hiddenTags: Object.freeze(["tag_sights"]),
    viewmodelUrl: 'viewmodel/t6_wpn_sniper_dsr50_view_lod0.glb',
    worldModelUrl: 'enemies/t6_wpn_sniper_dsr50_world_lod1.glb',
    scope: Object.freeze({
      modelUrl: 'viewmodel/t6_wpn_sniper_dsr50_scope_view_lod0.glb',
      offset: Object.freeze([-5.701, 0.0, 4.843]),
      zoomFov: 15,
      zoomLevels: Object.freeze([15, 15, 15]),
      overlay: 'ui/scope/scope_overlay_dsr50.png',
      idleAmount: 60,
      swayMaxAngle: 2,
    }),
    boltAction: true,
    magazineUrl: 'viewmodel/t6_attach_mag_dsr50_view_lod0.glb',
    // Authored attachment offset from the shipped dsr50_mp weapon file.
    magazineOffset: Object.freeze([-6.18, 0, 0.861]),
    magazineRotation: Object.freeze([0, 0, 0]),
    clips: Object.freeze({
      idle: 'viewmodel/anims/viewmodel_dsr50_idle.json',
      fire: 'viewmodel/anims/viewmodel_dsr50_fire.json',
      adsFire: 'viewmodel/anims/viewmodel_dsr50_ads_fire.json',
      reload: 'viewmodel/anims/viewmodel_dsr50_reload.json',
      reloadEmpty: 'viewmodel/anims/viewmodel_dsr50_reload_empty.json',
      rechamber: 'viewmodel/anims/viewmodel_dsr50_rechamber.json',
      adsRechamber: 'viewmodel/anims/viewmodel_dsr50_ads_rechamber.json',
    }),
  }),
  ballista: Object.freeze({
    id: 'ballista',
    name: 'Ballista',
    class: 'primary',
    role: 'Sniper rifle',
    slot: 11,
    sourceId: 'ballista',
    magazineSize: 7,
    reserveAmmo: 14,
    roundsPerMinute: 300,
    fireMode: 'single',
    damage: 95,
    fireTypeIcon: 'hud_mp_firerate_bolt',
    cardArt: 'ui/menu_mp_weapons_ballista_big.png',
    hiddenTags: Object.freeze(["tag_sights"]),
    viewmodelUrl: 'viewmodel/t6_wpn_sniper_ballista_view_lod0.glb',
    worldModelUrl: 'enemies/t6_wpn_sniper_ballista_world_lod1.glb',
    scope: Object.freeze({
      modelUrl: 'viewmodel/t6_wpn_sniper_ballista_scope_view_lod0.glb',
      offset: Object.freeze([5.312, 0.0, 4.737]),
      zoomFov: 15,
      zoomLevels: Object.freeze([15, 15, 15]),
      overlay: 'ui/scope/scope_overlay_ballista.png',
      idleAmount: 35,
      swayMaxAngle: 2,
    }),
    boltAction: true,
    magazineUrl: 'viewmodel/t6_attach_mag_ballista_view_lod0.glb',
    // Authored attachment offset from the shipped ballista_mp weapon file.
    magazineOffset: Object.freeze([5.799, 0, -0.395]),
    magazineRotation: Object.freeze([0, 0, 0]),
    clips: Object.freeze({
      idle: 'viewmodel/anims/viewmodel_ballista_idle.json',
      fire: 'viewmodel/anims/viewmodel_ballista_fire.json',
      adsFire: 'viewmodel/anims/viewmodel_ballista_ads_fire.json',
      reload: 'viewmodel/anims/viewmodel_ballista_reload.json',
      reloadEmpty: 'viewmodel/anims/viewmodel_ballista_reload_empty.json',
      rechamber: 'viewmodel/anims/viewmodel_ballista_rechamber.json',
      adsRechamber: 'viewmodel/anims/viewmodel_ballista_ads_rechamber.json',
    }),
  }),
  svu: Object.freeze({
    id: 'svu',
    name: 'SVU-AS',
    class: 'primary',
    role: 'Sniper rifle',
    slot: 12,
    sourceId: 'svu',
    magazineSize: 12,
    reserveAmmo: 24,
    roundsPerMinute: 417,
    fireMode: 'single',
    damage: 70,
    fireTypeIcon: 'hud_mp_firerate_single',
    cardArt: 'ui/menu_mp_weapons_svu_big.png',
    viewmodelUrl: 'viewmodel/t6_wpn_sniper_svu_view_lod0.glb',
    worldModelUrl: 'enemies/t6_wpn_sniper_svu_world_lod1.glb',
    scope: Object.freeze({
      modelUrl: 'viewmodel/t6_wpn_sniper_svu_scope_view_lod0.glb',
      offset: Object.freeze([4.253, -0.033, 6.839]),
      zoomFov: 20,
      zoomLevels: Object.freeze([20, 20, 20]),
      overlay: 'ui/scope/scope_overlay_svu.png',
      idleAmount: 26,
      swayMaxAngle: 2,
    }),
    boltAction: false,
    magazineUrl: 'viewmodel/t6_attach_mag_svu_view_lod0.glb',
    // Authored attachment offset from the shipped svu_mp weapon file.
    magazineOffset: Object.freeze([-5.784, 0, 0.095]),
    magazineRotation: Object.freeze([0, 0, 0]),
    clips: Object.freeze({
      idle: 'viewmodel/anims/viewmodel_svu_as_idle.json',
      fire: 'viewmodel/anims/viewmodel_svu_as_fire.json',
      adsFire: 'viewmodel/anims/viewmodel_svu_as_fire.json',
      reload: 'viewmodel/anims/viewmodel_svu_as_reload.json',
      reloadEmpty: 'viewmodel/anims/viewmodel_svu_as_reload_empty.json',
    }),
  }),
  as50: Object.freeze({
    id: 'as50',
    name: 'XPR-50',
    class: 'primary',
    role: 'Sniper rifle',
    slot: 13,
    sourceId: 'as50',
    magazineSize: 8,
    reserveAmmo: 16,
    roundsPerMinute: 375,
    fireMode: 'single',
    damage: 95,
    fireTypeIcon: 'hud_mp_firerate_single',
    cardArt: 'ui/menu_mp_weapons_as50_big.png',
    hiddenTags: Object.freeze(["tag_rail"]),
    viewmodelUrl: 'viewmodel/t6_wpn_sniper_xpr50_view_lod0.glb',
    worldModelUrl: 'enemies/t6_wpn_sniper_xpr50_world_lod1.glb',
    scope: Object.freeze({
      modelUrl: 'viewmodel/t6_wpn_sniper_xpr50_scope_view_lod0.glb',
      offset: Object.freeze([4.456, 0.0, 4.253]),
      zoomFov: 15,
      zoomLevels: Object.freeze([15, 15, 15]),
      overlay: 'ui/scope/scope_overlay_xpr50.png',
      idleAmount: 60,
      swayMaxAngle: 0.1,
    }),
    boltAction: false,
    // The XPR-50's clips were authored against a hands rig whose torso sits
    // 13 units ahead of the FBI viewhands' bind, and its idle carries no torso
    // track, so on the bind the receiver lands in the camera. This is the
    // torso pose its own ads_up clip opens on.
    torsoBind: Object.freeze([8.68, -3.97, -4.64]),
    magazineUrl: 'viewmodel/t6_attach_mag_xpr50_view_lod0.glb',
    // Authored attachment offset from the shipped as50_mp weapon file.
    magazineOffset: Object.freeze([6.332, 0, -0.345]),
    magazineRotation: Object.freeze([0, 0, 0]),
    clips: Object.freeze({
      idle: 'viewmodel/anims/viewmodel_xpr50_idle.json',
      fire: 'viewmodel/anims/viewmodel_xpr50_fire.json',
      adsFire: 'viewmodel/anims/viewmodel_xpr50_fire.json',
      reload: 'viewmodel/anims/viewmodel_xpr50_reload.json',
      reloadEmpty: 'viewmodel/anims/viewmodel_xpr50_reload_empty.json',
    }),
  }),

  // Secondaries. Pistol magazines are part of the gun model, so there is no
  // separate attachment to weld; the reload clips animate the gun's own
  // tag_clip. Each carries its own pistol-whip melee clip. The game starts a
  // pistol with two spare magazines.
  fiveseven: Object.freeze({
    id: 'fiveseven',
    name: 'Five-seven',
    class: 'secondary',
    role: 'Pistol',
    slot: 1,
    sourceId: 'fiveseven',
    magazineSize: 20,
    reserveAmmo: 40,
    roundsPerMinute: 750,
    fireMode: 'single',
    damage: 55,
    fireTypeIcon: 'hud_mp_firerate_single',
    cardArt: null,
    viewmodelUrl: 'viewmodel/t6_wpn_pistol_fiveseven_view_lod0.glb',
    worldModelUrl: 'enemies/t6_wpn_pistol_fiveseven_world_lod1.glb',
    magazineUrl: null,
    clips: Object.freeze({
      idle: 'viewmodel/anims/viewmodel_fn57_idle.json',
      fire: 'viewmodel/anims/viewmodel_fn57_fire.json',
      adsFire: 'viewmodel/anims/viewmodel_fn57_ads_fire.json',
      reload: 'viewmodel/anims/viewmodel_fn57_reload.json',
      reloadEmpty: 'viewmodel/anims/viewmodel_fn57_reload_empty.json',
      melee: 'viewmodel/anims/viewmodel_fn57_tactical_melee.json',
    }),
  }),
  fnp45: Object.freeze({
    id: 'fnp45',
    name: 'Tac-45',
    class: 'secondary',
    role: 'Pistol',
    slot: 2,
    sourceId: 'fnp45',
    magazineSize: 10,
    reserveAmmo: 20,
    roundsPerMinute: 625,
    fireMode: 'single',
    damage: 55,
    fireTypeIcon: 'hud_mp_firerate_single',
    cardArt: null,
    viewmodelUrl: 'viewmodel/t6_wpn_pistol_fnp45_view_lod0.glb',
    worldModelUrl: 'enemies/t6_wpn_pistol_fnp45_world_lod1.glb',
    magazineUrl: null,
    // Measured sight opening/post in j_gun coordinates (inches).
    adsSightAnchors: Object.freeze({
      front: Object.freeze([4.85, 0, 2.221]),
      rear: Object.freeze([-2.5, 0, 2.221]),
    }),
    clips: Object.freeze({
      idle: 'viewmodel/anims/viewmodel_fnp45_idle.json',
      fire: 'viewmodel/anims/viewmodel_fnp45_fire.json',
      adsFire: 'viewmodel/anims/viewmodel_fnp45_ads_fire.json',
      reload: 'viewmodel/anims/viewmodel_fnp45_reload.json',
      reloadEmpty: 'viewmodel/anims/viewmodel_fnp45_reload_empty.json',
      melee: 'viewmodel/anims/viewmodel_fnp45_tactical_melee.json',
    }),
  }),
  kard: Object.freeze({
    id: 'kard',
    name: 'KAP-40',
    class: 'secondary',
    role: 'Pistol',
    slot: 3,
    sourceId: 'kard',
    magazineSize: 15,
    reserveAmmo: 30,
    roundsPerMinute: 938,
    fireMode: 'auto',
    damage: 45,
    fireTypeIcon: 'hud_mp_firerate_auto',
    cardArt: 'ui/menu_mp_weapons_kard_big.png',
    viewmodelUrl: 'viewmodel/t6_wpn_pistol_kard_view_lod0.glb',
    worldModelUrl: 'enemies/t6_wpn_pistol_kard_world_lod1.glb',
    magazineUrl: null,
    // Measured sight opening/post in j_gun coordinates (inches).
    adsSightAnchors: Object.freeze({
      front: Object.freeze([7.5, 0, 2.999]),
      rear: Object.freeze([-1.5, 0, 2.999]),
    }),
    clips: Object.freeze({
      idle: 'viewmodel/anims/viewmodel_kard_idle.json',
      fire: 'viewmodel/anims/viewmodel_kard_fire.json',
      adsFire: 'viewmodel/anims/viewmodel_kard_ads_fire.json',
      reload: 'viewmodel/anims/viewmodel_kard_reload.json',
      reloadEmpty: 'viewmodel/anims/viewmodel_kard_reload_empty.json',
      melee: 'viewmodel/anims/viewmodel_kard_tactical_melee.json',
    }),
  }),
  beretta93r: Object.freeze({
    id: 'beretta93r',
    name: 'B23R',
    class: 'secondary',
    role: 'Pistol',
    slot: 4,
    sourceId: 'beretta93r',
    magazineSize: 15,
    reserveAmmo: 30,
    roundsPerMinute: 938,
    fireMode: 'burst',
    burstCount: 3,
    damage: 45,
    fireTypeIcon: 'hud_mp_firerate_burst',
    cardArt: null,
    viewmodelUrl: 'viewmodel/t6_wpn_pistol_b2023r_view_lod0.glb',
    worldModelUrl: 'enemies/t6_wpn_pistol_b2023r_world_lod1.glb',
    magazineUrl: null,
    adsSightAnchors: Object.freeze({
      rear: Object.freeze([-2.204, 0, 2.377]),
    }),
    clips: Object.freeze({
      idle: 'viewmodel/anims/viewmodel_beretta2023r_idle.json',
      fire: 'viewmodel/anims/viewmodel_beretta2023r_fire.json',
      adsFire: 'viewmodel/anims/viewmodel_beretta2023r_ads_fire.json',
      reload: 'viewmodel/anims/viewmodel_beretta2023r_reload.json',
      reloadEmpty: 'viewmodel/anims/viewmodel_beretta2023r_reload_empty.json',
      melee: 'viewmodel/anims/viewmodel_beretta2023r_tactical_melee.json',
    }),
  }),
});

export const WEAPON_IDS = Object.freeze(Object.keys(WEAPONS));

// Scope behaviour shared by every sniper, on top of the per-weapon `scope`.
// The world zooms as the sight comes up; the overlay lands at the top of the
// raise (adsZoomInFrac 0) and leaves at the first touch of the lower
// (adsZoomOutFrac 0.05). Sway is a slow figure of eight scaled by the file's
// adsIdleAmount; holding breath (Shift in the scope) steadies it for
// breathHoldSeconds and then it comes back.
export const SCOPE = Object.freeze({
  hipFov: 75,
  overlayInFrac: 0.985,
  overlayOutFrac: 0.95,
  // Degrees of sway per unit of adsIdleAmount, peak to peak, at rest.
  swayDegreesPerIdle: 0.011,
  breathHoldSeconds: 5,
  breathRecoverSeconds: 3,
  breathHoldSwayScale: 0.08,
  zoomSound: 'fly_scope_zoom',
});

/** Weapons of one class, in card order. */
export function weaponsOfClass(classId, table = WEAPONS) {
  return Object.values(table)
    .filter((weapon) => weapon.class === classId)
    .sort((a, b) => a.slot - b.slot);
}

// Legacy ids the debug API and old links still use.
export const WEAPON_ALIASES = Object.freeze({ hk416: 'm27' });

export function findWeapon(id, table = WEAPONS) {
  const key = String(id ?? '').toLowerCase();
  return table[WEAPON_ALIASES[key] ?? key] ?? null;
}

/** Soundbank alias prefix for a weapon: `wpn_<source>_<suffix>`. */
export function weaponCue(id, suffix, table = WEAPONS) {
  const weapon = findWeapon(id, table);
  return `wpn_${weapon?.sourceId ?? String(id).toLowerCase()}_${suffix}`;
}

// Equipment. The frag and the smoke share the M67 throw clips and the
// grenade's own physics in grenades.js; their numbers are frag_grenade_mp and
// willy_pete_mp verbatim. `fuse` is seconds from the pin, so a frag held for
// two seconds goes off 1.5 after it leaves the hand.
export const EQUIPMENT = Object.freeze({
  frag: Object.freeze({
    id: 'frag',
    name: 'Frag',
    class: 'lethal',
    role: 'Lethal grenade',
    slot: 1,
    kind: 'frag',
    count: 1,
    icon: 'ui/hud/hud_us_grenade.png',
    cardArt: null,
    fuse: 3.5,
    cookable: true,
    throwSpeed: 920,
    explosionRadius: 256,
    innerDamage: 200,
    outerDamage: 75,
    modelUrl: 'viewmodel/t6_wpn_grenade_frag_projectile_lod0.glb',
    throwTime: 0.365,
    sounds: Object.freeze({
      pin: 'wpn_grenade_pull_pin',
      throw: 'wpn_grenade_throw',
      bounce: 'wpn_grenade_bounce',
      explode: 'wpn_grenade_explode',
      explodeDistant: 'wpn_grenade_explode_dist',
      explodeLfe: 'wpn_grenade_explode_lfe',
    }),
  }),
  smoke: Object.freeze({
    id: 'smoke',
    name: 'Smoke',
    class: 'tactical',
    role: 'Tactical grenade',
    slot: 1,
    kind: 'smoke',
    count: 1,
    icon: 'ui/hud/hud_obit_tact_grenade.png',
    cardArt: null,
    // willy_pete_mp pops almost on release and its cloud stands for a while.
    fuse: 1.5,
    cookable: false,
    throwSpeed: 920,
    explosionRadius: 0,
    innerDamage: 0,
    outerDamage: 0,
    smokeRadius: 220,
    smokeDuration: 12,
    modelUrl: 'viewmodel/t6_wpn_grenade_smoke_projectile_lod0.glb',
    throwTime: 0.3,
    sounds: Object.freeze({
      pin: 'wpn_smoke_pull_pin_plyr',
      throw: 'wpn_grenade_throw',
      bounce: 'wpn_smoke_bounce',
      explode: 'wpn_smoke_grenade_explode',
      hissStart: 'wpn_smoke_hiss_start',
      hissLoop: 'wpn_smoke_hiss_lp',
      hissEnd: 'wpn_smoke_hiss_end',
    }),
  }),
});

export function equipmentOfClass(classId, table = EQUIPMENT) {
  return Object.values(table)
    .filter((item) => item.class === classId)
    .sort((a, b) => a.slot - b.slot);
}

// Melee, from knife_mp: every rifle's melee is the combat knife, one hit kills,
// and the swing lands meleeDelay into a meleeTime lockout. `range` is the
// engine's melee reach in inches and `lunge` how much further a target
// directly ahead pulls the hit, as the game's melee lunge does. Pistols use
// their own whip clip but the same numbers.
export const MELEE = Object.freeze({
  damage: 150,
  range: 64,
  lunge: 40,
  // Half-angle of the cone a target has to be inside, degrees.
  cone: 32,
  delay: 0.125,
  time: 0.8,
  knifeModelUrl: 'viewmodel/t6_wpn_knife_base_view_lod0.glb',
  knifeTag: 'tag_knife_attach',
  clips: Object.freeze({
    swipe: 'viewmodel/anims/viewmodel_m4m203_knife_melee_1.json',
    charge: 'viewmodel/anims/viewmodel_m4m203_knife_melee_2.json',
  }),
  sounds: Object.freeze({
    swing: 'wpn_melee_whoosh_plr',
    draw: 'wpn_melee_knife_draw_plr',
    hitBody: 'wpn_melee_knife_hit_body',
    hitOther: 'wpn_melee_knife_hit_other',
    exert: 'vox_melee_exert_plr',
  }),
});

// Grenade throw clips, shared by every hand-thrown grenade.
export const THROW_CLIPS = Object.freeze({
  pullPin: 'viewmodel/anims/viewmodel_m67_pullpin.json',
  throw: 'viewmodel/anims/viewmodel_m67_throw.json',
});

// A fresh class: what a player spawns with before touching create-a-class.
export const DEFAULT_LOADOUT = Object.freeze({
  primary: 'm27',
  secondary: 'fiveseven',
  lethal: 'frag',
  tactical: 'smoke',
});

/** A random loadout for a bot: any rifle, any pistol, always the two grenades. */
export function randomLoadout(random = Math.random, table = WEAPONS) {
  const pick = (list) => list[Math.floor(random() * list.length)]?.id ?? null;
  return {
    primary: pick(weaponsOfClass('primary', table)) ?? DEFAULT_LOADOUT.primary,
    secondary: pick(weaponsOfClass('secondary', table)) ?? DEFAULT_LOADOUT.secondary,
    lethal: DEFAULT_LOADOUT.lethal,
    tactical: DEFAULT_LOADOUT.tactical,
  };
}

/**
 * Loadout order for the weapon wheel and the number keys: the primary in slot
 * 1, the secondary in slot 2. Returns the id one step from `current`.
 */
export function nextHeldWeapon(loadout, current, step = 1) {
  const held = ['primary', 'secondary'].map((cls) => loadout?.[cls]).filter(Boolean);
  if (!held.length) return null;
  const index = Math.max(0, held.indexOf(current));
  return held[((index + step) % held.length + held.length) % held.length];
}
